"""start

Revision ID: a67c44b0fd80
Revises: 
Create Date: 2025-04-20 10:41:32.284784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a67c44b0fd80'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('properties',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('product_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_uid'], ['products.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('property_values',
    sa.Column('value_uid', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('property_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_uid'], ['properties.uid'], ),
    sa.PrimaryKeyConstraint('value_uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_values')
    op.drop_table('properties')
    op.drop_table('products')
    # ### end Alembic commands ###
