services:
  app:
    build:
      dockerfile: docker/Dockerfile
      context: ..
    environment:
      APP_CONFIG__DB__URL: postgresql+asyncpg://${SQL_USER}:${SQL_PASS}@pg:${SQL_PORT}/${SQL_BASE}
      APP_CONFIG__DB__ECHO: ${APP_CONFIG__DB__ECHO}
    ports:
      - "8000:8000"
    depends_on:
      pg:
        condition: service_healthy
    container_name: app_container_${HOSTNAME}

  pg:
    image: postgres:16.4
    environment:
      POSTGRES_DB: ${SQL_BASE}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASS}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 3
    container_name: app_pg_container_${HOSTNAME}
volumes:
  pgdata: